---
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

  # Database Connection Parameters from SSM
  DatabaseHost:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Database host
    Default: commute_database_host
  DatabaseUser:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Database user
    Default: commute_database_user
  DatabasePass:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Database pass
    NoEcho: true
    Default: commute_database_pass
  DatabaseName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Database name
    Default: commute_database_name

Resources:
  SnsToDb:
    Type: AWS::Serverless::Function
    Properties:
      Description: Commute SNS to Database
      Handler: index.handler
      Runtime: python2.7
      CodeUri: ./
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - sg-2d222258
        SubnetIds:
          - subnet-1a09626c
          - subnet-c8266490
          - subnet-3980ae04
          - subnet-9c5315b6
      Policies:
        - AmazonSNSFullAccess
        - AWSLambdaVPCAccessExecutionRole
      Environment:
        Variables:
          DATABASE_HOST: !Ref DatabaseHost
          DATABASE_USER: !Ref DatabaseUser
          DATABASE_PASS: !Ref DatabasePass
          DATABASE_NAME: !Ref DatabaseName
      Events:
        CommuteTopic:
          Type: SNS
          Properties:
            Topic: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:commute-traffic
