---
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  SnsToDb:
    Type: AWS::Serverless::Function
    Properties:
      Description: Commute SNS to Database
      Handler: index.handler
      Runtime: python3.6
      CodeUri: ./
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - sg-2d222258
        SubnetIds:
          - subnet-1a09626c
          - subnet-c8266490
          - subnet-3980ae04
          - subnet-9c5315b6
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSNSFullAccess
        - AmazonSSMReadOnlyAccess
      Events:
        CommuteTopic:
          Type: SNS
          Properties:
            Topic: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:commute-traffic
